akashic-games/pdi-browser

CHANGELOG.md
src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts
src/plugin/WebAudioPlugin/WebAudioPlayer.ts

WebAudioPlayer#stop と HTMLAudioPlayer#stop で、対象の audio がない場合でも g.AudioPlayer#stop を呼び出すように修正。
- なし

Update WebAudioPlayer#stop, HTMLAudioPlayer#stop

---

CHANGELOG.md
package.json
src/asset/HTMLImageAsset.ts

プライマリキャンバスの再利用を有効にするため `ImageElement#crossOrigin` を `"anonymous"` に設定します。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/img#Attributes

Add "anonymous" to image element

---

CHANGELOG.md
package.json
src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts

* `audio.play()`が二重に呼ばれていたため、html-exportされたゲーム実行時に`Uncaught (in promise) DOMException`というエラーが出ていた
* catchを行っていない方の`audio.play()`を削除した

fix HTMLAudioPlayer.ts

---

CHANGELOG.md
package.json
src/asset/HTMLImageAsset.ts

やってみて色々問題の発覚した `crossorigin` 属性を削除します。
変更点自明のためセルフマージします。

make v1.5.9: revert crossorigin attribute

---

CHANGELOG.md
package.json
src/asset/HTMLImageAsset.ts

`ImageAsset#hint#untainted` が true の場合、 `ImageElement#crossOrigin` に `"anonymous"` が付加されるように修正します。
#3 の本対応になります。

Add "anonymous" to image element when untainted flag is true

---

CHANGELOG.md
package.json
src/asset/XHRScriptAsset.ts

掲題どおり。スクリプトアセットの最終行が `//` コメントだと、スクリプトの前後につけている snippet の後半が巻き込まれてコメントアウトされてしまい、パースエラーが起きていました。
特に sourceMappingURL のコメントが末尾にある場合に直撃します。よく今まで問題になっていなかったという感じですが、 sandbox だと例外的に回避できる上、 akashic export で bundle してしまえば生じないので実運用上の発覚が遅れたようです。
修正自明のためセルフマージします。

Fix error for last line comments in script assets

---

CHANGELOG.md
package.json
src/plugin/WebAudioPlugin/WebAudioHelper.ts

pdi-browser が複数回ロードされていくと、 AudioContext のインスタンスが増加し、 Safari や Edge でエラーになる問題を修正します。具体的には、グローバル変数を作ってしまい、そこでインスタンスを共有します。
akashic-sandbox に組み込み、音声を鳴らすゲームが問題なく動作することを確認しています。

Share the AudioContext instance to avoid allocation faillure on Safari

---

CHANGELOG.md
package.json
src/Platform.ts

* コンテンツ破棄時に画像・音声を握り潰すための処理を`Platform#destroy()`に実装しました。
* `Platform#destroy()`で以下の処理を行うようにしました。
* surfaceの破棄
* 音量をミュートにする
* https://github.com/akashic-games/akashic-pdi/pull/1 がマージ且つpublishされた後に、package.jsonで最新バージョンの`@akashic/akashic-pdi`を指定

コンテンツ破棄時に画像・音声を握り潰すための対応

---

CHANGELOG.md
package.json
src/Platform.ts

* コンテンツ破棄時に画像・音声を握り潰すための処理を`Platform#destroy()`に実装しました。
* `Platform#destroy()`で以下の処理を行うようにしました。
* surfaceの破棄
* 音量をミュートにする
* https://github.com/akashic-games/akashic-pdi/pull/2 がマージ且つpublishされた後に、package.jsonで1系最新バージョンの`@akashic/akashic-pdi`を指定

コンテンツ破棄時に画像・音声を握り潰すための対応(v1)

---

src/index.ts
src/plugin/AudioPluginManager.ts
src/plugin/ProxyAudioPlugin/ProxyAudioAsset.ts
src/plugin/ProxyAudioPlugin/ProxyAudioHandlerSet.ts
src/plugin/ProxyAudioPlugin/ProxyAudioPlayer.ts
src/plugin/ProxyAudioPlugin/ProxyAudioPlugin.ts

- 実際の音声再生処理をすべてコールバックに委ねる `AudioPlugin` 実装、 `ProxyAudioPlugin` を追加します。
- このクラスがコンストラクタ引数を取らざるを得ないことを鑑み、 `AudioPluginManager#tryInstallPlugins()` に、クラスでなく `AudioPlugin` 自体も渡せるようにします (この場合 new せずそのまま使う)。

Add ProxyAudioPlugin

---

CHANGELOG.md
package.json
src/canvas/context2d/Context2DRenderer.ts

`g.Renderer#begin()` , `g.Renderer#end()` の呼び出し時に `CanvasSurfaceContext#save()` , `CanvasSurfaceContext#restore()` を呼ぶようにします。
これにより、 `g.Pane` など内部で別の `CanvasSurfaceContext` を生成しているエンティティの描画時に、初期状態の `CanvasRenderingContext2D` が引き継がれてしまっていたバグを修正します。

バックサーフェスの描画時に context の状態が正常に初期化されていなかった件の修正

---

renovate.json

* pdi-browserでも基本的にはakashic-cliと同じように、renovateで行うバージョンアップはminorかpatchだけにしたいのでそのようにrenovate.jsonに修正を入れました。

majorバージョンアップをrenovateの対象外にする対応

---

CHANGELOG.md
package.json
src/handler/InputAbstractHandler.ts
src/handler/MouseHandler.ts
src/handler/TouchHandler.ts

* マウスが画面外に飛んだ場合pointMove等のイベントが強制的に終了されてしまう問題への対応を行いました。この対応によってマウス操作が画面外に飛んだ場合でもイベントが止まらずに継続されるようになります。
* InputAbstractHandlerにcanvasから見た相対的なoffsetを算出する`getOffsetPositionFromInputView()`を作成して、マウスイベントで座標取得のためにそのメソッドを使うように変更
この変更を加えたpdi-broserを含むengine-filesで以下の確認を行いました。
* コンテンツ画面内でpointDownイベントを起こした後、画面外でもpointMoveやpointUpイベントが継続できること
* mouseHandlerと同様にtouchHandlerを用いても上記ができること

MouseHandler が画面外で反応しない問題への対応

---

CHANGELOG.md
package.json
src/ContainerController.ts
src/Platform.ts

`Platform#setRendererRequirement()` を2度呼び出したとき、2度目の処理でnull参照によって例外が発生します。
これを解決するため、primary surfaceの削除責務をPlatformからcontainerControllerに移します。

move surface.destroy duty from Platform to ContainerController

---

CHANGELOG.md
package-lock.json
package.json
src/canvas/GlyphFactory.ts

* https://github.com/akashic-games/akashic-engine/pull/189 の対応でg.Glyphがdeprecatedになるので、g.Glyphの代わりにg.GlyphLikeを使うようにする対応を行いました。

g.Glyphの利用箇所でg.GlyphLikeを使うよう差し替える対応

---

CHANGELOG.md
package-lock.json
package.json
src/ContainerController.ts
src/InputHandlerLayer.ts
src/handler/InputAbstractHandler.ts

https://github.com/akashic-games/akashic-engine/pull/179 で導入された `g.PlatformPointEvent` などへの追従が漏れていました。 game-driver の追従は https://github.com/akashic-games/game-driver/pull/27 で行われていますが、これに対応する pdi-browser 側の追従が行われていません。
このため、まっさらから npm i するとビルドが通らなくなっていました。 これを修正します。
なおこれは、const enum が akashic-pdi から akashic-engine に移動・改名されたことへの追従です。そのためこの修正の前後で、生成された JS に差分はないはずです (＝ #69 での動作確認は正しくない状態で行われたものの、動作上の実害はなかったはず)。念のため、あらためてこの状態で engine-files を生成して akashic-sandbox に組み込み、 v3 向けの手元の適当なコンテンツが動作することを確認しました。
#69 の作業中に発覚したため、 enum-to-str ブランチへの PR になっています。

follow g.PlatformPointEvent

---

CHANGELOG.md
package.json
src/canvas/webgl/WebGLShaderProgram.ts

シェーダの `uniform.value` に `Float32Array` が渡された場合に取得できない不具合の修正。
配列チェックで `Array.isArray(value)` で判定していたが、`Array.isArray()` では TypedArray のインスタンスは常に false を返す仕様のため。
`ArrayBuffer.isView()` と `DataView` インスタンスを弾く条件でも可能だが、 `uniform.value` の型が `number | Int32Array | Float32Array` のため number 以外のチェックとする。

Fix array check in ShaderUniform.value

---

CHANGELOG.md
package.json
src/canvas/context2d/CanvasSurfaceContext.ts

restore() により描画状態が復元されるが、 `CanvasSurfaceContext` のメンバ変数 `_currentfillStyle`, `_currentGlobalAlpha`, `_currentGlobalCompositeOperation` は現在の状態を保持したままになり `context` との状態が異なる問題を修正。
_currentXXXXX の変数名を _contextXXXXX へ変更

Fix variable state with CanvasSurfaceContext#restore()

---

CHANGELOG.md
package-lock.json
package.json
src/canvas/shims/CanvasDisposer.ts
src/canvas/shims/CanvasSurfaceFactory.ts
src/canvas/shims/SurfaceFactory.ts
tsconfig.json

参照されなくなった `CanvasSurface` を検知し、関連付けられた `HTMLCanvasElement` のメモリを開放するように修正します。
以下のミニマムコンテンツにて正常に dispose されていることを確認しています。
<details>
<summary>動作確認</summary>
* register, dispose 時にログを追加
```javascript
module.exports = () => {
const scene = new g.Scene({
game: g.game
});
scene.onLoad.add(() => {
scene.onUpdate.add(() => {
const surface = g.game.resourceFactory.createSurface(100, 100);
const sprite = new g.Sprite({
scene,
src: surface,
width: 32,
height: 32
});
scene.append(sprite);
scene.setTimeout(() => {
sprite.destroy();
}, 10);
});
});
g.game.pushScene(scene);
}
```
</details>

fix: 未参照の CanvasSurface に関連付けられた HTMLCanvasElement を開放するように

---

src/plugin/WebAudioPlugin/WebAudioPlayer.ts

オーディオアセットのループ機能を、 systemId が `sound` の場合のみ適用します。
同様に、 `AudioAsset#offset` による部分再生を `music` の場合のみ適用します。
関連： https://github.com/akashic-games/pdi-browser/pull/250
- なし

enable offset only systemId:sound

---

package.json

一時的にPhantomJSの実行を止めるため、testスクリプトからtestemの実行コマンドを削除

stop testem temporary

---

CHANGELOG.md
package.json
src/ContainerController.ts
src/InputHandlerLayer.ts
src/Platform.ts
src/handler/InputEventHandler.ts
src/handler/MouseTouchEventHandler.ts
src/handler/PointerEventHandler.ts
src/handler/__tests__/InputEventHandler.spec.ts

掲題どおり。
`PointerEventHandler` が依存する PointerEvent が利用できない環境のため、フォールバックとして MouseEvent/TouchEvent を使う`MouseTouchEventHandler` を追加します。
- `PointerEventHandler` の PointerEvent に関連しない部分を `InputEventHandler` として切り出し
- `InputEventHandler` の派生クラスとして `MouseTouchEventHandler` を追加
ビルドした結果を engine-files に取り込んで akashic serve で動かして、デバッガで強制的に `MouseTouchEventHandler` を利用させることで、mouse/touch 両ハンドラが妥当な座標の `g.PointEvent` を生成してくることを確認しています。

feat: reintroduce mouse/touch event handler as fallback

---

CHANGELOG.md
package-lock.json
package.json
src/ContainerController.ts
src/InputHandlerLayer.ts
src/Platform.ts

* `InputHandler` の `view` に `tabindex: 0` を付与します。
* `tabindex` を操作するメソッド `Platform#setTabindex()` を追加します。

feat: add Platform#setTabindex()

---

CHANGELOG.md
package-lock.json
package.json
src/handler/MouseTouchEventHandler.ts

`MouseTouchEventHandler` において `button` の値が一部 `PointerEventHandler` と異なってしまう問題を修正します。
1. マウス左ボタンを押下
1. カーソルを移動
1. マウス左ボタンを離す
という一連の動作において、修正前と修正後の挙動の差異を簡易的な時系列として以下の表にまとめます。
| イベント種別 | `button` の値 | 動作 |
| -- | :--: | -- |
|`PointDownEvent`| 0  | マウス左ボタン押下 |
|`PointMoveEvent`| **0** | カーソル移動 |
|`PointMoveEvent`| **0** | カーソル移動 |
| ...            | .. | ... |
|`PointMoveEvent`| **0** | カーソル移動 |
|`PointUpEvent`  | 0  | マウス左ボタン離す |
| イベント種別 | `button` の値 | 動作 |
| -- | :--: | -- |
|`PointDownEvent`| 0  | マウス左ボタン押下 |
|`PointMoveEvent`| **-1** | カーソル移動 |
|`PointMoveEvent`| **-1** | カーソル移動 |
| ...            | .. | ... |
|`PointMoveEvent`| **-1** | カーソル移動 |
|`PointUpEvent`  | 0  | マウス左ボタン離す |
<details>
<summary>中身を展開</summary>
また、 `PointerEventHandler` と `MouseTouchEventHandler` でそれぞれの挙動を比較しています。 …

fix: `MouseTouchEventHandler` において `button` の値が一部 `PointerEventHandler` と異なってしまう問題を修正

---

CHANGELOG.md
package-lock.json
package.json
src/InputHandlerLayer.ts

掲題どおり。 
ある種の環境でペンタブレットでゲーム画面をドラッグした際、ブラウザウィンドウ全体のスクロールなど (いわゆる direct manipulation) が起きるのを抑止します。これは akashic serve などでは再現しませんが、[ドラッグを使うサンプルデモ](https://akashic-games.github.io/demo/?title=point-event-button) で以下の条件で確認できます。
- Windows の Chrome や Firefox を使用している
- ワコムのタブレットを使用している
- ワコムのタブレット設定の「Windows Ink を使う」が有効になっている
- ブラウザウィンドウが狭い (スクロールできる状態)
ただし上のデモは pdi-browser を使っておらず、この PR 自体では修正されません。(ブラウザの開発者ツールで、この PR と同じように `touch-action` をつけて問題を解消することを目視しています)
akashic serve に組み込み、以下の環境で意図しない影響が出ないことを確認しています。
- Mac Chrome 上の akashic serve
- Mac Chrome (Device Mode) 上の akashic serve

fix: fix dragging by digitizer

---

CHANGELOG.md
package-lock.json
package.json
src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts

`HTMLAudioPlayer#play()` で同一の audio を連続するとエラーとなる問題を修正。
現在再生中の audio とこれから再生する audio が同じ場合は、現在再生中の audio を先頭から再生し、再生する予定の audio は何もしないように修正。

Fix htmlaudioplayer

---

CHANGELOG.md
package-lock.json
package.json
src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts

offset+duration の値が音声の長さを上回るオーディオアセットをループ再生した場合、
2週目以降はオーディオを停止できなくなる現象を修正します。
- なし

skip super.stop when loop

---

src/plugin/HTMLAudioPlugin/AudioElementPlayer.ts
src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts
src/plugin/HTMLAudioPlugin/HTMLAudioPlayerContext.ts

`HTMLAudioPlayer` をリファクタリングします。
- `HTMLAudioPlayer` と `HTMLAudioElement` の間に `HTMLAudioPlayerContext` を追加します。
- `duration` が未定義の場合は全体を再生します
- `offset` が未定義の場合は最初から再生します
- `loopOffset` が未定義の場合はループ時に最初から再生します

refactor: refactor HTMLAudioPlayer
