CHANGELOG.md, package.json, src/handler/TouchHandler.ts
Android Chrome環境でゲームを実行した際、アセットローディング中にタッチイベントが発生した場合、 エラーが発生する現象を解決します。
- なし
=> fix cancelable error

CHANGELOG.md, package.json
amflowのminor更新によるバージョンアップ(minor version)
=> Update by minor version-up of amflow

src/plugin/ProxyAudioPlugin/ProxyAudioHandlerSet.ts, src/plugin/ProxyAudioPlugin/ProxyAudioPlayer.ts
=> ProxyAudioHandlerSetのI/F変更

renovate.json
=> Upate renovate.json

CHANGELOG.md, package.json
https://github.com/akashic-games/akashic-engine/pull/124 のminor更新に追従します。
pdi-browserの変更はありません。
=> bump minor version

package-lock.json, package.json, src/asset/XHRScriptAsset.ts
2.0.0-beta.0 の prerelease 準備です。
=> Prepare 2.0.0-beta.0

.travis.yml
travis.ymlの対象からnode-v8を削除し、node-v12を追加
=> remove node8 from travis.yml and add node12

src/ContainerController.ts, src/Platform.ts
https://github.com/akashic-games/pdi-browser/pull/53 のv3対応です。
v3向けakashic-sandbox環境で動作確認済みです。
=> Fix surface destroy duty v3

CHANGELOG.md, package.json
依存しているplaylogとamflowのメジャーバージョンを更新する対応を行いました
=> update inner modules (v1.9.0)

CHANGELOG.md, package.json
依存しているplaylogとamflowのメジャーバージョンを更新する対応を行いました
=> update inner modules (v0.13.0)

CHANGELOG.md, package-lock.json, package.json, src/ContainerController.ts, src/InputHandlerLayer.ts, src/ResourceFactory.ts, src/asset/HTMLVideoAsset.ts, src/canvas/GlyphFactory.ts, src/canvas/context2d/Context2DRenderer.ts, src/canvas/webgl/WebGLRenderer.ts, src/canvas/webgl/WebGLRenderingState.ts, src/canvas/webgl/WebGLSharedObject.ts, src/handler/InputAbstractHandler.ts
掲題どおり。 akashic-games/akashic-engine#211 に追従します。
akahsic-engine の反映が済むまで CI を通りません。手元では当該の akashic-engine の PR と組み合わせて akashic-sandbox で最低限のコンテンツが動作することを確認しています。
=> follow akashic-engine#211 (enum to string literal types)

CHANGELOG.md, package-lock.json, package.json, src/plugin/HTMLAudioPlugin/HTMLAudioAsset.ts, src/plugin/WebAudioPlugin/WebAudioAsset.ts
- akashic-engine@3.0.0-beta.24に追従します。
- `g.PathUtil.addExtname()` -> `g.PdiCommonUtil.addExtname` へ変更
**関連PR**: https://github.com/akashic-games/akashic-engine/pull/229
=> follow akashic-engine@3.0.0-beta.24

CHANGELOG.md, package.json
以下の依存モジュールを更新します。
* `@akashic/akashic-pdi`
* `@akashic/amflow`
* `@akashic/playlog`
=> Make version 1.10.0

package.json
#84 にてモジュールのバージョンを上げ忘れてしまったため、再度バージョンを上げ直します。
=> Bump version 0.14.0

CHANGELOG.md, package.json
=> [AEv1] Follow @akashic/amflow@3.0.0

CHANGELOG.md, package.json
=> Follow @akashic/amflow@3.0.0

CHANGELOG.md, package-lock.json, package.json
=> [AEv3] Follow @akashic/amflow@3.0.0

src/ResourceFactory.ts, src/canvas/Context2DRenderer.ts, tsconfig.json
`noImplicitThis, strictBindCallApply, strictFunctionTypes` を有効にします。
https://github.com/akashic-games/pdi-browser/pull/116 の ae1x 対応です。
=> use noImplicitThis, strictBindCallApply, strictFunctionTypes, for ae1x

src/ResourceFactory.ts, src/canvas/webgl/WebGLShaderProgram.ts, tsconfig.json
`noImplicitThis, strictBindCallApply, strictFunctionTypes` を有効にします。
https://github.com/akashic-games/pdi-browser/pull/116 の ae2x 対応です。
=> use noImplicitThis, strictBindCallApply, strictFunctionTypes, for ae2x

src/ResourceFactory.ts, src/canvas/webgl/WebGLShaderProgram.ts, tsconfig.json
`noImplicitThis, strictBindCallApply, strictFunctionTypes` を有効にします。
=> use noImplicitThis, strictBindCallApply, strictFunctionTypes

.github/workflows/release.yml
`--ignore-scripts` をつけると PhantomJS のインストールに失敗するようなので削除します。
cf: https://github.com/akashic-games/pdi-browser/runs/3408842901
=> fix(ci): remove --ignore-scripts flag

CHANGELOG.md, package-lock.json, package.json
=> v2.1.0; use pdi-types@1.2.0

renovate.json
renovate の設定を変更します。
* `@akashic` スコープのモジュールをまとめるように
* patch, minor はそれぞれまとめて、major はモジュールごとにまとめて PullRequest を出すように
* 一部無効なものを有効に
=> chore: adjust renovate config

.github/workflows/release.yml, package-lock.json, package.json, src/ResourceFactory.ts, src/asset/SVGImageAsset.ts, src/canvas/context2d/Context2DRenderer.ts
VGImageAsset の実装を追加します。
関連:
* https://github.com/akashic-games/pdi-types/pull/20
* https://github.com/akashic-games/game-configuration/pull/7
* https://github.com/akashic-games/pdi-common-impl/pull/19
* https://github.com/akashic-games/akashic-engine/pull/311
=> feat: SVGImageAsset の実装を追加

.github/workflows/release.yml, CHANGELOG.md, package-lock.json, package.json, src/ResourceFactory.ts, src/asset/SVGImageAsset.ts, src/canvas/context2d/Context2DRenderer.ts
main ブランチに #154, #157 をマージします。
=> feat: SVGImageAsset の実装を追加 (main)

renovate.json
* 以下のrenovateのPRについては自動マージできるようにした
* `@akashic`以外のライブラリのpatchバージョンの更新
* `@akashic`以外のライブラリのminorバージョンの更新
=> be able to merge automatically renovate PR

CHANGELOG.md, package-lock.json, package.json, src/plugin/AudioPlayer.ts
`AudioPlayer` の生成時に、volume と mute に AudioSystem の値を設定している不具合を修正。
=> Fix initial values of AudioPlayer volume and mute

CHANGELOG.md, package-lock.json, package.json
@akashic/trigger 更新に伴うパッチバージョンアップ。
セルフマージとします。
=> Bump version to 2.2.2

.github/workflows/release.yml, .github/workflows/test.yml, package.json, renovate.json
* CI の Node のバージョンを 14, 16 系に更新
* renovate.json を共通設定に変更
=> chore: ワークフローの修正など

.github/workflows/release.yml, CHANGELOG.md, package-lock.json, package.json
=> Rerelase 2.3.0

package-lock.json, package.json
akashic/eslint-config を 1.1.1 へ更新します。
renovate の #241 へセルフマージします。
=> Update eslint config

src/plugin/HTMLAudioPlugin/__tests__/HTMLAudioAsset.spec.ts, src/plugin/HTMLAudioPlugin/__tests__/HTMLAudioPlayer.spec.ts, src/plugin/HTMLAudioPlugin/__tests__/HTMLAudioPlugin.spec.ts, src/plugin/ProxyAudioPlugin/__tests__/ProxyAudioAsset.spec.ts, src/plugin/ProxyAudioPlugin/__tests__/ProxyAudioPlayer.spec.ts, src/plugin/ProxyAudioPlugin/__tests__/ProxyAudioPlugin.spec.ts, src/plugin/ProxyAudioPlugin/__tests__/helpers/MockProxyAudioHandlerSet.ts, src/plugin/WebAudioPlugin/__tests__/WebAudioAsset.spec.ts, src/plugin/WebAudioPlugin/__tests__/WebAudioPlayer.spec.ts, src/plugin/WebAudioPlugin/__tests__/WebAudioPlugin.spec.ts, src/plugin/WebAudioPlugin/__tests__/helpers/mock.ts, src/plugin/__tests__/helpers/MockAudioSystem.ts
音声に関するユニットテスト (主に `ProxyAudioPlugin`) を追加します。
=> chore(test): 音声のユニットテストを追加

CHANGELOG.md, package-lock.json, package.json, src/plugin/WebAudioPlugin/WebAudioPlayer.ts
=> Bump v2.4.1

CHANGELOG.md, package-lock.json, package.json, src/asset/AudioAsset.ts, src/plugin/HTMLAudioPlugin/HTMLAudioAsset.ts, src/plugin/HTMLAudioPlugin/HTMLAudioPlugin.ts, src/plugin/HTMLAudioPlugin/__tests__/HTMLAudioAsset.spec.ts, src/plugin/ProxyAudioPlugin/ProxyAudioAsset.ts, src/plugin/WebAudioPlugin/WebAudioAsset.ts, src/plugin/WebAudioPlugin/WebAudioPlugin.ts, src/plugin/WebAudioPlugin/__tests__/WebAudioAsset.spec.ts
* AudioAssetの`hint.extensions`で指定された拡張子を優先的に利用するように変更
* AudioAssetの拡張子としてm4aも利用できるように
=> specify extension of AudioAsset by AudioAsset#hint

CHANGELOG.md, package.json, src/ResourceFactory.ts, src/plugin/HTMLAudioPlugin/HTMLAudioPlayer.ts
HTMLAudio 利用時に offset を扱えるようにします。
関連： https://github.com/akashic-games/pdi-browser/pull/250
- なし
=> Enable offset html audio

package.json
https://github.com/akashic-games/pdi-browser/pull/262 の残件です。
package.json の version 更新が漏れていたため2.4.3に更新します。
- なし
=> bump package.json version 2.4.3

CHANGELOG.md, package-lock.json, package.json, src/Platform.ts
`Platform#usingPointerEvents` を追加します。
=> feat: add Platform#usingPointerEvents

src/canvas/Renderer.ts, src/canvas/context2d/Context2DRenderer.ts, src/canvas/webgl/WebGLRenderer.ts
レンダラにコンテキストを返すメソッド `getContext()` を追加します。
=> feat: add Renderer#getContext()

src/canvas/Renderer.ts, src/canvas/context2d/Context2DRenderer.ts, src/canvas/webgl/WebGLRenderer.ts, src/canvas/webgl/WebGLSharedObject.ts
レンダラに蓄積された描画バッファを即時実行する `Renderer#flush()` を追加します。
=> feat: add Renderer#flush()

CHANGELOG.md, package-lock.json, package.json
=> chore: v2.5.1

CHANGELOG.md, package.json
@akashic/amflowと@akashic/playlogと@akashic/akashic-pdiのminor更新に伴うバージョンアップ
=> update akashic modules

CHANGELOG.md, package.json
=> v0.16.0; update to akashic-pdi@1.16.0

package.json
Reverts akashic-games/pdi-browser#282
=> Revert "temporarily remove phantomjs"

CHANGELOG.md, package-lock.json, package.json, src/handler/PointerEventHandler.ts
`PointerEvent` サポート環境において `PointMoveEvent#button`, `PointUpEvent#button` に対応します。
=> feat: `PointerEvent` サポート環境において `PointMoveEvent#button`, `PointUpEvent#button` に対応

CHANGELOG.md, package-lock.json, package.json, src/ContainerController.ts, src/InputHandlerLayer.ts, src/Platform.ts
`tabindex` を `tabIndex` (tab + index) に置換します。
影響は軽微だろうという前提のもとでパッチバージョンの更新とします。
内容については別で議論済みのためセルフマージします。
=> fix: replace tabindex to tabIndex

CHANGELOG.md, package-lock.json, package.json, src/ResourceFactory.ts, src/canvas/RenderingHelper.ts, src/canvas/shims/SurfaceFactory.ts, src/canvas/webgl/WebGLSharedObject.ts
* `@akashic/pdi-types@1.14.0` に更新
* `RendererCandidate` をサポート
* `WebGLRenderer` で部分的に depth buffer をサポートするように
* https://github.com/akashic-games/pdi-types/pull/71
* https://github.com/akashic-games/game-configuration/pull/54
=> feat: support `RendererCandidate`
